version: '3'

services:
     web:
       image: nginx:alpine
       ports:
           - "8080:80"
       volumes:
           - ./public_html:/public_html
           - ./conf.d:/etc/nginx/conf.d
       networks:
           - nginxphp
       deploy:
           replicas: 1

     php:
       image: php:7.1.11-fpm-alpine
       volumes:
           - ./public_html:/public_html
       expose:
           - 9000
       networks:
           - nginxphp
       deploy:
           replicas: 1
       
     portainer:
       image: portainer/portainer
       ports:
           - 9000:9000
       volumes:
           - /var/run/docker.sock:/var/run/docker.sock
       deploy:
           replicas: 1

networks:
     nginxphp:
